### ISSUE TITLE
TestVisibilitySplit with istio is not stable

### ISSUE THREAD

**Issue by nak3** [knative-extensions/net-gateway-api#185]
TestVisibilitySplit with istio often fails.
Here is some information:

- example [log 1](https://github.com/knative-sandbox/net-gateway-api/runs/4178678069?check_suite_focus=true), [log 2](https://github.com/knative-sandbox/net-gateway-api/runs/4178678180?check_suite_focus=true)
- The issue is that [this `HTTPRouteFilter`](https://github.com/knative-sandbox/net-gateway-api/blob/0218953e1beef961b6ba0df7a0ed8eb6c1d02405/test/conformance/ingressv2/visibility.go#L122-L129) does not set the header so it shows `0%` of request received.
- It happens with conformance test only. e2e with controller does not have the issue.
- `TestPercentage`, which is the same test but just public access, does not cause any error.
- gateway-api v0.4.0 with istio-1.13-alpha.8aea949750d59a51b322d36ec7cac2c60cea5ac8 also has this issue.

**Comment by dprotaso** [comment]
Closing - test is stable as of Apr 2nd 2024 - see test grid
<img width="930" alt="Screenshot 2024-04-02 at 1 51 57 PM" src="https://github.com/knative-extensions/net-gateway-api/assets/18562/ad3e8554-9225-4a5c-b1bc-b91d91ef83db">

https://testgrid.k8s.io/r/knative-own-testgrid/net-gateway-api#continuous-istio
