### ISSUE TITLE
Figure out gateway features are behind flags for the last couple Contour releases and enable them

### ISSUE THREAD

**Issue by carlisia** [knative-extensions/net-gateway-api#360]

**Comment by dprotaso** [comment]
Milestone tracking 
https://github.com/orgs/projectcontour/projects/4/views/6

Outstanding v0.60 work - https://github.com/projectcontour/contour/issues/4738

**Comment by dprotaso** [comment]
Closing this out Contour doesn't have feature flags for Gateway Features anymore
