### ISSUE TITLE
Figure out gateway features are behind flags for the last couple Istio releases and enable them

### ISSUE THREAD

**Issue by carlisia** [knative-extensions/net-gateway-api#361]

**Comment by dprotaso** [comment]
Skipped tests are tracked here: https://github.com/istio/istio/blob/master/tests/integration/pilot/gateway_conformance_test.go#L71-L73

**Comment by dprotaso** [comment]
Closing this out - Istio is only skipping some mesh tests. So we don't need to track enabling features
