### ISSUE TITLE
[Upstream] Better management of `Spec.Listeners`

### ISSUE THREAD

**Issue by carlisia** [knative-extensions/net-gateway-api#363]
Ref.: https://github.com/kubernetes-sigs/gateway-api/discussions/1248.

**Comment by dprotaso** [comment]
/lifecycle frozen

I've created a GEP issue to help address this - https://github.com/kubernetes-sigs/gateway-api/issues/1713

**Comment by dprotaso** [comment]
Clsoing as a dupe of https://github.com/knative-extensions/net-gateway-api/issues/317
