### ISSUE TITLE
[Upstream] Enable > 2k TLS Services

### ISSUE THREAD

**Issue by carlisia** [knative-extensions/net-gateway-api#368]
Ref.:nhttps://github.com/kubernetes-sigs/gateway-api/discussions/1246.

**Comment by dprotaso** [comment]
/lifecycle frozen

I've created a GEP issue to help address this - https://github.com/kubernetes-sigs/gateway-api/issues/1713

**Comment by dprotaso** [comment]
Closing as duplicate of https://github.com/knative-extensions/net-gateway-api/issues/363
