### ISSUE TITLE
KIngress e2e conformance test checklist for Istio

### ISSUE THREAD

**Issue by carlisia** [knative-extensions/net-gateway-api#383]
### This checklist tracks that all Knative KIngress e2e conformance tests for this Gateway API implementation are passing.

- [X] basics/TestBasics
- [X] basics/TestBasicsHTTP2
- [X] grpc/TestGRPC
- [X] grpc/TestGRPCSplit
- [x] headers/tags/TestTagHeaders
- [X] headers/TestProbeHeaders
- [X] headers/TestPreSplitSetHeaders
- [X] headers/TestPostSplitSetHeaders
- [x] host-rewrite/TestRewriteHost (https://github.com/knative-extensions/net-gateway-api/issues/533)
- [X] hosts/TestMultipleHosts
- [ ] httpoption/TestHTTPOption
- [X] dispatch/TestPath
- [X] dispatch/TestPercentage
- [X] dispatch/TestPathAndPercentageSplit
- [X] dispatch/TestRule
- [ ] retry/TestRetry
- [X] timeout/TestTimeout
- [X] tls/TestIngressTLS
- [X] update/TestUpdate
- [X] visibility/TestVisibility
- [X] visibility/TestVisibilitySplit
- [X] visibility/TestVisibilityPath
- [X] ingressclass/TestIngressClass
- [X] websocket/TestWebsocket
- [X] websocket/TestWebsocketSplit

**Comment by dprotaso** [comment]
Closing this - we are tracking this in the repo and eventually we'll have tests that run continously - see https://github.com/knative-extensions/net-gateway-api/issues/621
