### ISSUE TITLE
KIngress conformance test checklist for Contour

### ISSUE THREAD

**Issue by carlisia** [knative-extensions/net-gateway-api#384]
### This checklist tracks that all Knative KIngress e2e conformance tests for this Gateway API implementation are passing.

- [X] basics/TestBasics
- [x] basics/TestBasicsHTTP2
- [x] grpc/TestGRPC
- [x] grpc/TestGRPCSplit
- [x] headers/tags/TestTagHeaders
- [X] headers/TestProbeHeaders
- [X] headers/TestPreSplitSetHeaders
- [X] headers/TestPostSplitSetHeaders
- [x] host-rewrite/TestRewriteHost (https://github.com/knative-extensions/net-gateway-api/issues/533)
- [X] hosts/TestMultipleHosts
- [ ] httpoption/TestHTTPOption
- [X] dispatch/TestPath
- [X] dispatch/TestPercentage
- [X] dispatch/TestPathAndPercentageSplit
- [X] dispatch/TestRule
- [x] retry/TestRetry
- [X] timeout/TestTimeout
- [X] tls/TestIngressTLS
- [ ] update/TestUpdate
- [X] visibility/TestVisibility
- [X] visibility/TestVisibilitySplit
- [x] visibility/TestVisibilityPath
- [X] ingressclass/TestIngressClass
- [x] websocket/TestWebsocket
- [x] websocket/TestWebsocketSplit

**Comment by sunjayBhatia** [comment]
contour supports gRPCRoute (on main) now if that is sufficient to try out the grpc tests!

**Comment by dprotaso** [comment]
@sunjayBhatia we don't create GRPCRoutes unfortunately and I don't think it makes sense for Knative to do so.

Revision updates can change the backend protocol so we're hoping to just use HTTPRoute and then rely on this GEP https://github.com/kubernetes-sigs/gateway-api/pull/1979 as a way to signal the backend protocol.

**Comment by sunjayBhatia** [comment]
As of https://github.com/projectcontour/contour/commit/d802a885e33df9b95a0dd0369bc53997038750cd Contour now supports websocket upgrades on Gateway API generated routes

**Comment by dprotaso** [comment]
Closing this - we are tracking this in the repo and eventually we'll have tests that run continously - see https://github.com/knative-extensions/net-gateway-api/issues/621
