### ISSUE TITLE
Do not use contour-operator

### ISSUE THREAD

**Issue by nak3** [knative-extensions/net-gateway-api#495]
https://github.com/projectcontour/contour-operator is archived and 1.25+ is not available.
The script still uses operator to deploy Contour so we need to fix them.

**Comment by AmanSarraf** [comment]
can I take this issue?

**Comment by nak3** [comment]
/assign @AmanSarraf 
Sure! Thank you so much :pray:

**Comment by AmanSarraf** [comment]
hello @nak3 , I have started working on this issue can you please tell me more about what I need to perform to fix this issue , also please let me know if there's any way to test the changes

**Comment by nak3** [comment]
You can refer to the [README](https://github.com/knative-sandbox/net-gateway-api/blob/main/README.md).

For the initial step, can you update the README to stop using https://raw.githubusercontent.com/projectcontour/contour-operator/... below in README but some other files in the repo https://github.com/projectcontour/contour  (or you may need to create something) ?

```
kubectl apply -f "https://raw.githubusercontent.com/projectcontour/contour-operator/${CONTOUR_VERSION}/examples/operator/operator.yaml"
```

**Comment by dprotaso** [comment]
@AmanSarraf are you still working on this?

**Comment by AmanSarraf** [comment]
Hi @dprotaso , I am currently not working on this issue, I may continue after next week . Thanks

**Comment by dprotaso** [comment]
OK - sorta related https://github.com/knative-extensions/net-gateway-api/issues/536
