### ISSUE TITLE
net-gateway-api shouldn't re-release Gateway API CRDs

### ISSUE THREAD

**Issue by dprotaso** [knative-extensions/net-gateway-api#539]
We shouldn't be shipping the Gateway API CRDs

https://github.com/knative-extensions/net-gateway-api/blob/main/config/100-gateway-api.yaml

In places where we need to install Gateway API we should probably use similar steps as istio outlines

https://istio.io/latest/docs/tasks/traffic-management/ingress/gateway-api/#setup

```sh
kubectl get crd gateways.gateway.networking.k8s.io &> /dev/null || \
  { kubectl kustomize "github.com/kubernetes-sigs/gateway-api/config/crd?ref=v0.8.0-rc1" | kubectl apply -f -; }
```

We'll want to update our docs as well

**Comment by dprotaso** [comment]
We'll need to tweak serving's e2e testing here

https://github.com/knative/serving/tree/main/third_party/gateway-api-latest

**Comment by gabo1208** [comment]
@dprotaso I don't quite follow what I need to do for serving, if you can explain a bit further

**Comment by dprotaso** [comment]
>  But I don't know if I have to install them for the istio head and latest plus the api gateway test cases. Is that the case?

Just the gateway test cases - we stage those files here
https://github.com/knative/serving/blob/eac93b072bab30ccb9fd6fb49aca4c7e28fa95ab/test/e2e-networking-library.sh#L25-L26

We want to make sure that continues working when we stop shipping the gateway api resource in our `net-gateway-api.yaml` . We could simplify this a bit and include a separate file in a release with the gateway api crds we want

This could be done here

eg. https://github.com/knative-extensions/net-gateway-api/blob/bd2d2610fab9946be0d63955b5201ea30679fc38/hack/release.sh#L24-L28

**Comment by dprotaso** [comment]
I'll leave this issue open (so it doesn't close when your PR merges) until we resolve the serving repo testing
