### ISSUE TITLE
Add envoy gateway to testing suite

### ISSUE THREAD

**Issue by dprotaso** [knative-extensions/net-gateway-api#566]
Continue to work done here https://github.com/knative-extensions/net-gateway-api/pull/469

cc @arkodg

**Comment by dprotaso** [comment]
Depends on https://github.com/knative-extensions/net-gateway-api/issues/621

Also envoy gateway doesn't work because it doesn't support adding request headers after a traffic split (backend filter)

**Comment by arkodg** [comment]
thanks @dprotaso for driving the work to integrate Envoy Gateway into Knative !

**Comment by dprotaso** [comment]
np!
