### ISSUE TITLE
Contour External has ExternalName Services Support

### ISSUE THREAD

**Issue by dprotaso** [knative-extensions/net-gateway-api#638]
In theory we don't need this since serving can handle returning an IP address via the KIngress

https://github.com/knative-extensions/net-gateway-api/blob/0e92b90271098f28518ed0292abac863a2acfbce/third_party/contour/gateway-external.yaml#L38-L39

**Comment by dprotaso** [comment]
Note: If we set the IP address in KIngress Status then serving will use it properly

https://github.com/knative/serving/pull/11843

**Comment by dprotaso** [comment]
https://github.com/knative/networking/blob/1d9a7cfb2ee119e581ba164fa1d152889efcf8a1/pkg/apis/networking/v1alpha1/ingress_types.go#L303

**Comment by KauzClay** [comment]
/unassign

oops, I meant to assign myself to this one: https://github.com/knative-extensions/net-gateway-api/issues/665
