### ISSUE TITLE
Find a generic way for matching the port by the endpoint lister instead of port name 

### ISSUE THREAD

**Issue by nader-ziada** [knative-extensions/net-gateway-api#668]
As a follow up to PR #658 which adds the port names used by contour, we need a general way of solving this that isn't specific to an implementation.

The code matching on the port name on the endpoints seems to be different between implementations, so might be a good idea to investigate using the K8s service or something else instead

**Comment by dprotaso** [comment]
Dupe of https://github.com/knative-extensions/net-gateway-api/issues/663
