### ISSUE TITLE
[cilium] It is not accessible unless helloworld-go-00001.default.svc.cluster.local

### ISSUE THREAD

**Issue by kahirokunn** [knative-extensions/net-gateway-api#717]
Accessed via the gateway api in cilium 1.15.4 with the following results.

```
~ $ curl helloworld-go.default
curl: (6) Could not resolve host: helloworld-go.default
~ $ curl helloworld-go-00001.default
Error getting active endpoint: revision.serving.knative.dev "" not found
~ $ curl helloworld-go-00001.default.svc
Error getting active endpoint: revision.serving.knative.dev "" not found
~ $ curl helloworld-go-00001.default.svc.cluster
curl: (6) Could not resolve host: helloworld-go-00001.default.svc.cluster
~ $ curl helloworld-go-00001.default.svc.cluster.local
Hello Go Sample v1!
```

**Comment by dprotaso** [comment]
I'm pretty sure we add all the hostnames 

https://github.com/knative-extensions/net-gateway-api/blob/cc122e38ef685261d26544d2a7dbae68c8345d6e/pkg/reconciler/ingress/resources/httproute.go#L224-L227

What do you see in your HTTPRoute?

**Comment by dprotaso** [comment]
@kahirokunn just following up here

**Comment by kahirokunn** [comment]
Sorry, I haven't had time to re-examine this one.
I will share the results and the scripts etc. I used when I tested it next time!
Thx 🙏

**Comment by CheyenneForbes** [comment]
this works
`wget -O- --header="Host: http-bin-00001.zxe.svc.cluster.local" http://172.27.0.5:80/get`

but this doesnt:
`wget -O- --header="Host: http-bin.zxe.svc.cluster.local" http://172.27.0.5:80/get`

**Comment by dprotaso** [comment]
@CheyenneForbes are you using cillium? 

We haven't tested it out yet to see what's broken.  I'd open an issue with cillium about that route.

**Comment by CheyenneForbes** [comment]
Yes, I am using Cilium, I'll open the issue there and link this issue

**Comment by CheyenneForbes** [comment]
@dprotaso I applied the same HTTPRoute rules for a non-knative service and its working ok

**Comment by dprotaso** [comment]
> http-bin.zxe.svc.cluster.local

most likely is going to the activator if it's scaled to zero - I'm wonder if you need to allow cross namespace connectivity to the knative-serving namespace

**Comment by CheyenneForbes** [comment]
I'm already using 

```
kind: Gateway
...
spec:
  listeners:
    - allowedRoutes:
        namespaces:
          from: All
```

**Comment by CheyenneForbes** [comment]
found this issue also by @kahirokunn 

https://github.com/cilium/cilium/issues/24495

ExternalName seems to be the issue

**Comment by CheyenneForbes** [comment]
@CheyenneForbes did you ever find a way around this issue?
